### ISSUE TITLE
Zeta variation with fixed tau

### ISSUE THREAD

**Issue by gehara** [isaacovercast/PTA#18]
Output shows variation on zeta values even with fixed tau, or no prior on tau. We should either prevent this to happen and have zeta = 1 when tau is fixed or throw an error.

**Comment by isaacovercast** [comment]
But tau can be fixed and the proportion of co-expanding taxa can still be less than 1, no? Maybe I don't understand correctly the problem.

**Comment by isaacovercast** [comment]
Fixed. If tau is fixed then zeta is set to 1.
